<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Morph</RootNamespace>
    <AssemblyName>Morph</AssemblyName>
    <Company>BatSoft</Company>
    <Product>Morph</Product>
    <Copyright>Copyright © BatSoft 2011</Copyright>
    <Version>1.0.0</Version>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
