<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Morph\Morph\Morph.csproj" />
    <ProjectReference Include="..\..\..\Morph\Morph.Daemon.Client\Morph.Daemon.Client.csproj" />
    <ProjectReference Include="..\Basic\Basic.csproj" />
  </ItemGroup>

</Project>
