<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>MorphDemoBookingServer</RootNamespace>
    <AssemblyName>BookingServer</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Bat.Library\Bat.Library.Logging\Bat.Library.Logging.csproj" />
    <ProjectReference Include="..\..\..\Morph\Morph\Morph.csproj" />
    <ProjectReference Include="..\..\..\Morph\Morph.Daemon.Client\Morph.Daemon.Client.csproj" />
    <ProjectReference Include="..\Booking\Booking.csproj" />
  </ItemGroup>

</Project>
